/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: { ignoreDuringBuilds: true },
  images: {
    unoptimized: true,
  },
  async redirects() {
    const OLD_URLS = [
      { source: '/autoalarmy', destination: '/sofistikovane-zabezpecenie' },
      { source: '/autoalarmy/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/tajne-vypinace', destination: '/sofistikovane-zabezpecenie' },
      { source: '/tajne-vypinace/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/tajny-vypinac', destination: '/sofistikovane-zabezpecenie' },
      { source: '/tajny-vypinac/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/motoralarmy', destination: '/sofistikovane-zabezpecenie' },
      { source: '/motoralarmy/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/handsfree', destination: '/sofistikovane-zabezpecenie' },
      { source: '/handsfree/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/zederlock', destination: '/sofistikovane-zabezpecenie' },
      { source: '/zederlock/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/alarm-pre-motorky', destination: '/sofistikovane-zabezpecenie' },
      { source: '/alarm-pre-motorky/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/ukradnute-auto-za-par-sekund', destination: '/sofistikovane-zabezpecenie' },
      { source: '/ukradnute-auto-za-par-sekund/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/deaktivacia-system-start-stop', destination: '/sofistikovane-zabezpecenie' },
      { source: '/deaktivacia-system-start-stop/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/telefonne-sady', destination: '/sofistikovane-zabezpecenie' },
      { source: '/telefonne-sady/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/autodiagnostika', destination: '/sofistikovane-zabezpecenie' },
      { source: '/autodiagnostika/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/tempomaty', destination: '/sofistikovane-zabezpecenie' },
      { source: '/tempomaty/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/doplnky-pre-motocykle', destination: '/sofistikovane-zabezpecenie' },
      { source: '/doplnky-pre-motocykle/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/katastrofa-len-3-auta-z-236-s-bezklucovym-pristupom-odolali-zlodejom-co-to-vase', destination: '/sofistikovane-zabezpecenie' },
      { source: '/katastrofa-len-3-auta-z-236-s-bezklucovym-pristupom-odolali-zlodejom-co-to-vase/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/gsm-autoalarm', destination: '/pasivny-monitoring' },
      { source: '/gsm-autoalarm/', destination: '/pasivny-monitoring/' },
      { source: '/gps', destination: '/pasivny-monitoring' },
      { source: '/gps/', destination: '/pasivny-monitoring/' },
      { source: '/monitoring', destination: '/pasivny-monitoring' },
      { source: '/monitoring/', destination: '/pasivny-monitoring/' },
      { source: '/medzinarodny-system-conex', destination: '/pasivny-monitoring' },
      { source: '/medzinarodny-system-conex/', destination: '/pasivny-monitoring/' },
      { source: '/medzinarodny-system-conex/connex-yellow', destination: '/pasivny-monitoring' },
      { source: '/medzinarodny-system-conex/connex-yellow/', destination: '/pasivny-monitoring/' },
      { source: '/medzinarodny-system-conex/connex-orange-plus', destination: '/pasivny-monitoring' },
      { source: '/medzinarodny-system-conex/connex-orange-plus/', destination: '/pasivny-monitoring/' },
      { source: '/medzinarodny-system-conex/connex-blue-pro', destination: '/pasivny-monitoring' },
      { source: '/medzinarodny-system-conex/connex-blue-pro/', destination: '/pasivny-monitoring/' },
      { source: '/how-it-works', destination: '/sofistikovane-zabezpecenie' },
      { source: '/how-it-works/', destination: '/sofistikovane-zabezpecenie/' },
      { source: '/contact', destination: '/kontakt' },
      { source: '/contact/', destination: '/kontakt/' },
      { source: '/contact-request', destination: '/kontakt' },
      { source: '/contact-request/', destination: '/kontakt/' },
      { source: '/cena-montaze', destination: '/kontakt' },
      { source: '/cena-montaze/', destination: '/kontakt/' },
      { source: '/zavolajte-mi', destination: '/kontakt' },
      { source: '/zavolajte-mi/', destination: '/kontakt/' },
      { source: '/referencie-2', destination: '/' },
      { source: '/referencie-2/', destination: '/' },
      { source: '/referencie-od-vas', destination: '/' },
      { source: '/referencie-od-vas/', destination: '/' },
      { source: '/dielna', destination: '/' },
      { source: '/dielna/', destination: '/' },
      { source: '/nasa-praca', destination: '/' },
      { source: '/nasa-praca/', destination: '/' },
      { source: '/odbornici', destination: '/' },
      { source: '/odbornici/', destination: '/' },
      { source: '/videa', destination: '/' },
      { source: '/videa/', destination: '/' },
      { source: '/caste-otazky', destination: '/' },
      { source: '/caste-otazky/', destination: '/' },
      { source: '/zaujimave-clanky-a-odkazy', destination: '/' },
      { source: '/zaujimave-clanky-a-odkazy/', destination: '/' },
      { source: '/generali-sos-partner', destination: '/' },
      { source: '/generali-sos-partner/', destination: '/' },
      { source: '/obchod', destination: '/' },
      { source: '/obchod/', destination: '/' },
      { source: '/kosik', destination: '/' },
      { source: '/kosik/', destination: '/' },
      { source: '/kontrola-objednavky', destination: '/' },
      { source: '/kontrola-objednavky/', destination: '/' },
      { source: '/moj-ucet', destination: '/' },
      { source: '/moj-ucet/', destination: '/' },
    ];
    return OLD_URLS.map(({ source, destination }) => ({
      source,
      destination,
      permanent: true,
    }));
  },
};

export default nextConfig;
